# Site settings
title: "Alex Hahn | CV"
description: "Alex Hahn's public CV."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Alex Hahn          "
resume_title:                   "Data Scientist"
resume_contact_email:           "AlexHahn15@gmail.com"
resume_contact_telephone:       "(714) 566-5635"
resume_contact_address:         "Los Angeles, CA"
resume_header_contact_info: "Los Angeles, CA | (714) 566-5635 | AlexHahn15@gmail.com"
# resume_header_intro: ""

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
# resume_section_skills:          false
resume_section_recognition:     true
# resume_section_links:           false
resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  # resume_github_url:            "https://github.com/hahnalex"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/hahnalex"
  resume_website_url:           "https://alexhahn.io"
  resume_instagram_url:         "https://www.instagram.com/alexhahnphoto/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
